//! Aggregate THIRD_PARTY_NOTICES.md from `cargo metadata` license fields.

use anyhow::{Context, Result};
use cargo_metadata::MetadataCommand;
use std::fs;

pub fn run() -> Result<()> {
    let metadata = MetadataCommand::new().exec().context("cargo metadata")?;
    let mut entries: Vec<(String, String, String)> = vec![];
    for pkg in &metadata.packages {
        let license = pkg.license.clone().unwrap_or_else(|| "UNKNOWN".to_string());
        entries.push((pkg.name.clone(), pkg.version.to_string(), license));
    }
    entries.sort();

    let mut out = String::new();
    out.push_str("# Third-Party Notices\n\n");
    out.push_str("Generated by `cargo xtask check-licenses`. Do not edit by hand.\n\n");
    out.push_str("| Crate | Version | License |\n|---|---|---|\n");
    for (name, version, license) in &entries {
        out.push_str(&format!("| `{name}` | {version} | {license} |\n"));
    }
    fs::write("THIRD_PARTY_NOTICES.md", out).context("write THIRD_PARTY_NOTICES.md")?;

    let unknown: Vec<_> = entries.iter().filter(|(_, _, l)| l == "UNKNOWN").collect();
    if !unknown.is_empty() {
        eprintln!(
            "check-licenses: WARNING — {} packages have no license field: {}",
            unknown.len(),
            unknown.iter().map(|(n, _, _)| n.as_str()).collect::<Vec<_>>().join(", ")
        );
        eprintln!("check-licenses: resolve before release (hard fail removed for Phase 0)");
    }
    println!("check-licenses: ok ({} packages)", entries.len());
    Ok(())
}
